name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
        
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: ./src
      run: docker build . --file Docker.Dns/Dockerfile --tag docker-dns:0.0.$GITHUB_RUN_NUMBER -o type=docker
    
    - name: Tag Git Commit
      uses: actions/github-script@v6
      with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/build-0.0.${context.runNumber}`,
              sha: context.sha
            })
            
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
       
    - name: Tag Docker Image
      run: |
        docker tag docker-dns:0.0.$GITHUB_RUN_NUMBER ${{ secrets.DOCKERHUB_USERNAME }}/docker-dns:0.0.$GITHUB_RUN_NUMBER
        docker tag docker-dns:0.0.$GITHUB_RUN_NUMBER ${{ secrets.DOCKERHUB_USERNAME }}/docker-dns:latest
      
    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-dns:0.0.$GITHUB_RUN_NUMBER
